apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
    version: 0.0.1
spec:
  containers:
  - name: myapp
    image: adityashahi/myapp:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000